name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      uses: actions/checkout@v3

      - name: Install dependencies
      run: sudo upt update && sudo apt install -y make g++

      - name: Build project
      run: make

