name: LabWork2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y make g++

      - name: Build project
        working-directory: LabWork2
        run: make

      - name: Run tests
        working-directory: LabWork2
        run: make test

